### ISSUE TITLE
Latest version breaks commands

### ISSUE THREAD

**Issue by Grandev-0** [TreeOfSelf/PandaAntiSpam#1]
No commands can be run with the latest vers panda-anti-spam-1.0.1_1.21.4 without it crashing with this:
`[18:20:56] [Render thread/ERROR]: Writing packet: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@b05be42[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@4633926e[Wrapped task = com.replaymod.recording.packet.PacketListener$$Lambda/0x0000021484d15788@6c81a37e]] rejected from java.util.concurrent.ThreadPoolExecutor@e78de2e[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 20011] at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081) ~[?:?] at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841) ~[?:?] at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376) ~[?:?] at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?] at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:785) ~[?:?] at knot/com.replaymod.recording.packet.PacketListener.save(PacketListener.java:205) ~[replaymod-1.21-2.6.19.jar:?] at knot/com.replaymod.recording.packet.PacketListener.lambda$save$1(PacketListener.java:193) ~[replaymod-1.21-2.6.19.jar:?] at knot//MC/net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:162) [client-intermediary.jar:?] at knot//MC/net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [client-intermediary.jar:?] at knot//MC/net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:136) [client-intermediary.jar:?] at knot//MC/net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:121) [client-intermediary.jar:?] at knot//MC/net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1240) [client-intermediary.jar:?] at knot//MC/net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882) [client-intermediary.jar:?] at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?] at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?] at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] [18:20:56] [Render thread/INFO]: [voicechat] Clearing audio channels [18:20:56] [Render thread/INFO]: [voicechat] Stopping microphone thread [18:20:56] [Render thread/INFO]: [voicechat] Disconnecting voicechat [18:20:56] [Render thread/INFO]: Stopping worker threads [18:20:56] [Render thread/WARN]: Client disconnected with reason: Internal Exception: java.lang.NoSuchMethodError: 'boolean net.minecraft.class_3222.method_64475(int)'`

**Comment by TreeOfSelf** [comment]
I'm not seeing anything related to the mod in your error log, and I have 2 somewhat active servers running the same version without issue.  Have you tried it without the voicechat/replay mod as those are mentioned in your log? 

Also- as mentioned on the Modrinth page, this is a server-side mod, not client-side. There shouldn't be any reason to have this running alongside replaymod as that is a client-side only mod.

**Comment by Grandev-0** [comment]
> I'm not seeing anything related to the mod in your error log, and I have 2 somewhat active servers running the same version without issue. Have you tried it without the voicechat/replay mod as those are mentioned in your log?
> 
> Also- as mentioned on the Modrinth page, this is a server-side mod, not client-side. There shouldn't be any reason to have this running alongside replaymod as that is a client-side only mod.

That was the kick message from the server

**Comment by TreeOfSelf** [comment]
> > I'm not seeing anything related to the mod in your error log, and I have 2 somewhat active servers running the same version without issue. Have you tried it without the voicechat/replay mod as those are mentioned in your log?
> > Also- as mentioned on the Modrinth page, this is a server-side mod, not client-side. There shouldn't be any reason to have this running alongside replaymod as that is a client-side only mod.
> 
> That was the kick message from the server

I see, are you sure you are running the correct version of Fabric? The version you are posting about (as the filename suggests) is for 1.21.4. The error you got disconnected with would lead me to believe you are not on 1.21.4 but using the 1.21.4 version of the mod.

**Comment by Grandev-0** [comment]
> > > I'm not seeing anything related to the mod in your error log, and I have 2 somewhat active servers running the same version without issue. Have you tried it without the voicechat/replay mod as those are mentioned in your log?
> > > Also- as mentioned on the Modrinth page, this is a server-side mod, not client-side. There shouldn't be any reason to have this running alongside replaymod as that is a client-side only mod.
> > 
> > 
> > That was the kick message from the server
> 
> I see, are you sure you are running the correct version of Fabric? The version you are posting about (as the filename suggests) is for 1.21.4. The error you got disconnected with would lead me to believe you are not on 1.21.4 but using the 1.21.4 version of the mod.

The server is 1.21.1 using fabric 1.16.9 and the 1.21.x version of the mod and that was my 1.21.1 client

**Comment by TreeOfSelf** [comment]
1.21.x version of the mod? That doesn't exist. Check your original post, you are using the 1.21.4 version. Just go back to using the 1.21.1 version if you want to stay on 1.21.1

**Comment by TreeOfSelf** [comment]
I see Modrinth is automatically marking my versions with 1.21.x 
I'll try and make sure next time I upload to specifically mark the correct version. Sorry for the confusion.
